class Questhins {
  static List<String> questions1 = [
    'Do you have abdominal pain',
    'Do you have chills',
    'Do you have fever',
    'do you have muscle joint pain',
    'Do you have abdomen swelling',
    'Do you have coughing',
    'Do you have difficulty concenrtrating',
    'Do you have swollen legs',
    'Do you have night sweats',
    'Do you have pain in neck',
    'Do you have upper belly area',
    'Do you have weight loss ?',
    'Do you have pain on shollder left',
    'Do you have irregular heart beat',
    'Do you have poor appetite',
    'Do you have weakness'
  ];
  static List<String> questions2 = [
    'Do you have rabid or irregular breathing',
    'Do you have fatigue',
    'Do you have dizziness',
    'do you have consciousness',
    'Do you have light headedness',
    'Do you have discomfort in arm',
    'Do you have wheezing',
    'Do you have heart beat changes',
    'Do you have dry',
    'Do you have persistent cough',
    'Do you have skin rashes',
    'Do you have cold sweat',
    'Do you have discomfort in leg',
    'Do you have Nausea',
    'Do you have pain in left arm',
    'Do you have cough',
  ];
  static List<String> questions3 = [
    'Do you have abnormal growth',
    'Do you have stroke',
    'Do you have chest pressure',
    'do you have pain in neck',
    'Do you have feeding difficulties',
    'Do you have poor weight gain',
    'Do you have sign of infection',
    'Do you have changes in temperature',
    'Do you have night sweats',
    'Do you have increased heart rate',
    'Do you have dizziness',
    'Do you have pain in leg',
    'Do you have fatigue',
    'Do you have pain in right arm',
    'Do you have rabid weight gain',
    'Do you have decreased Urine output',
  ];
  static List<String> questions4 = [
    'Do you have change in vision',
    'Do you have numbness',
    'Do you have chest tightness',
    'do you have chest pressure',
    'Do you have severe pain',
    'Do you have difficulty of breathing',
    'Do you have loss of consciousness',
    'Do you have pallor or profuse sweating',
    'Do you have headaches',
    'Do you have dizziness',
    'Do you have Anxiety',
    'Do you have strong heart beat',
  ];
}
